import os

FAST_POSTGRES_PASSWORD = os.getenv("FAST_POSTGRES_PASSWORD")
FAST_POSTGRES_USER = os.getenv("FAST_POSTGRES_USER")
FAST_POSTGRES_DB = os.getenv("FAST_POSTGRES_DB")
FAST_POSTGRES_PORT = os.getenv("FAST_POSTGRES_PORT")
FAST_POSTGRES_HOST = os.getenv("FAST_POSTGRES_HOST")
