version: '3.9'

services:

  pgdb:
    image: postgres:alpine3.19
    restart: always
    env_file:
      - Thinking_Machine_Dagster_Project/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - thinking-machine-network

  pgadmin4:
    image: dpage/pgadmin4:8.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - thinking-machine-network
    depends_on:
      - pgdb

  web:
    build: "./FastAPI/"
    env_file:
      - FastAPI/.env
    ports:
      - "8000:80"
    networks:
      - thinking-machine-network
    depends_on:
      - pgdb


  dagster:
    build: Thinking_Machine_Dagster_Project/
    env_file:
      - Thinking_Machine_Dagster_Project/.env
    networks:
      - thinking-machine-network
    depends_on:
      - pgdb
    ports:
      - "3000:3000"


volumes:
  pg_data:
  pgadmin_data:

networks:
  thinking-machine-network:
    driver: bridge
    name: thinking-machine-network
