version: '3.9'

volumes:
  pg_data:
  pgadmin_data:

services:

  pgdb:
    image: postgres:alpine3.19
    restart: always
    env_file:
      - Thinking-Machine-Project/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin4:
    image: dpage/pgadmin4:8.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    build: "./FastAPI/"
    environment:
      - FastAPI/.env
    ports:
      - "8000:80"
